const cropsData = [
    {
        id: 1,
        name_en: "Wheat",
        name_hi: "गेहूं",
        soil_en: "Loamy, Clayey",
        soil_hi: "दोमट, चिकनी",
        season_en: "Rabi",
        season_hi: "रबी",
        duration: 120,
        sowing_en: "November",
        sowing_hi: "नवंबर",
        harvest_en: "April",
        harvest_hi: "अप्रैल",
        seed_en: "Kalyansona, Sonalika, HD-2967",
        seed_hi: "कल्याणसोना, सोनालिका, एचडी-2967",
        fertilizer_en: "Urea, DAP, Potash",
        fertilizer_hi: "यूरिया, डीएपी, पोटाश",
        water_en: "4-6 Irrigations",
        water_hi: "4-6 सिंचाई",
        yield: "18-22 Quintals",
        cost: "15,000",
        profit: "28,000",
        active: true,
        risk_level: "Low",
        images: [],
        about_en: "Wheat is one of the most important cereal crops in the world.",
        about_hi: "गेहूं दुनिया की सबसे महत्वपूर्ण अनाज फसलों में से एक है।",
        cost_breakdown: { seed: 2500, fertilizer: 4000, pesticide: 1500, labor: 5000, irrigation: 2000 },
        advisory_en: { best_sowing: "Nov", harvest_timing: "Hard grain", fertilizer_schedule: "Basal DAP", seed_quantity: "40-50kg" },
        advisory_hi: { best_sowing: "नवंबर", harvest_timing: "कठोर दाने", fertilizer_schedule: "आधार डीएपी", seed_quantity: "40-50 किलो" },
        diseases: [
            { name_en: "Yellow Rust", name_hi: "पीला रतुआ", cause: "Fungus", occurrence_en: "Cool, moist", occurrence_hi: "ठंडा, नम", symptoms_en: "Yellow stripes", symptoms_hi: "पीली धारियां", prevention_en: "Resistant varieties", prevention_hi: "प्रतिरोधी किस्में", treatment_en: "Propiconazole", treatment_hi: "प्रोपिकोनाज़ोल" }
        ],
        tips_en: "Irrigate at CRI stage.",
        tips_hi: "सीआरआई चरण पर सिंचाई करें।"
    },
    {
        id: 2,
        name_en: "Rice",
        name_hi: "चावल (धान)",
        soil_en: "Clayey, Loamy",
        soil_hi: "चिकनी, दोमट",
        season_en: "Kharif",
        season_hi: "खरीफ",
        duration: 150,
        sowing_en: "June - July",
        sowing_hi: "जून - जुलाई",
        harvest_en: "October - November",
        harvest_hi: "अक्टूबर - नवंबर",
        seed_en: "IR-64, Basmati, Pusa-1121",
        seed_hi: "आईआर-64, बासमती, पूसा-1121",
        fertilizer_en: "Nitrogen, Zinc, NPK",
        fertilizer_hi: "नाइट्रोजन, जिंक, एनपीके",
        water_en: "High (Standing water)",
        water_hi: "उच्च (खड़ा पानी)",
        yield: "25-30 Quintals",
        cost: "20,000",
        profit: "38,000",
        active: true,
        risk_level: "Medium",
        images: [],
        about_en: "Rice is the primary staple food for a large part of the world population.",
        about_hi: "चावल दुनिया की आबादी के एक बड़े हिस्से के लिए प्राथमिक मुख्य भोजन है।",
        cost_breakdown: { seed: 3000, fertilizer: 5000, pesticide: 2000, labor: 8000, irrigation: 2000 },
        advisory_en: { best_sowing: "June-July", harvest_timing: "Golden yellow grains", fertilizer_schedule: "Basal P&K", seed_quantity: "20-25kg" },
        advisory_hi: { best_sowing: "जून-जुलाई", harvest_timing: "सुनहरे पीले दाने", fertilizer_schedule: "आधार पी और के", seed_quantity: "20-25 किलो" },
        diseases: [
            { name_en: "Blast", name_hi: "ब्लास्ट", cause: "Fungus", occurrence_en: "Humid", occurrence_hi: "आर्द्र", symptoms_en: "Diamond spots", symptoms_hi: "हीरे के आकार के धब्बे", prevention_en: "Resistant varieties", prevention_hi: "प्रतिरोधी किस्में", treatment_en: "Tricyclazole", treatment_hi: "ट्राइसाइक्लाज़ोल" }
        ],
        tips_en: "Maintain water level during tillering.",
        tips_hi: "कल्ले निकलते समय जल स्तर बनाए रखें।"
    },
    {
        id: 3,
        name_en: "Soybean",
        name_hi: "सोयाबीन",
        soil_en: "Black Soil, Loamy",
        soil_hi: "काली मिट्टी, दोमट",
        season_en: "Kharif",
        season_hi: "खरीफ",
        duration: 100,
        sowing_en: "June",
        sowing_hi: "जून",
        harvest_en: "September",
        harvest_hi: "सितंबर",
        active: true,
        risk_level: "Medium",
        images: [],
        about_en: "Soybean is a major source of vegetable protein and oil.",
        about_hi: "सोयाबीन वनस्पति प्रोटीन और तेल का एक प्रमुख स्रोत है।",
        diseases: [],
        tips_en: "Ensure seed treatment with Rhizobium.",
        tips_hi: "राइजोबियम के साथ बीज उपचार सुनिश्चित करें।"
    },
    {
        id: 4,
        name_en: "Cotton",
        name_hi: "कपास",
        soil_en: "Black Soil",
        soil_hi: "काली मिट्टी",
        season_en: "Kharif",
        season_hi: "खरीफ",
        duration: 180,
        sowing_en: "May - June",
        sowing_hi: "मई - जून",
        harvest_en: "November - December",
        harvest_hi: "नवंबर - दिसंबर",
        active: true,
        risk_level: "High",
        images: [],
        about_en: "Cotton is known as 'White Gold'.",
        about_hi: "कपास को 'सफेद सोना' के रूप में जाना जाता है।",
        diseases: [],
        tips_en: "Use pheromone traps.",
        tips_hi: "फेरोमोन ट्रैप का उपयोग करें।"
    },
    {
        id: 5,
        name_en: "Maize",
        name_hi: "मक्का",
        soil_en: "Alluvial, Red Soil",
        soil_hi: "जलोढ़, लाल मिट्टी",
        season_en: "Kharif / Rabi",
        season_hi: "खरीफ / रबी",
        duration: 110,
        sowing_en: "June / October",
        sowing_hi: "जून / अक्टूबर",
        harvest_en: "September / February",
        harvest_hi: "सितंबर / फरवरी",
        active: true,
        risk_level: "Low",
        images: [],
        about_en: "Maize is a versatile cereal.",
        about_hi: "मक्का एक बहुमुखी अनाज है।",
        diseases: [],
        tips_en: "Apply Zinc Sulphate.",
        tips_hi: "जिंक सल्फेट लगाएं।"
    },
    {
        id: 8,
        name_en: "Sugarcane",
        name_hi: "गन्ना",
        soil_en: "Loamy, Black, Alluvial",
        soil_hi: "दोमट, काली, जलोढ़",
        season_en: "Perennial",
        season_hi: "बारहमासी",
        duration: 365,
        sowing_en: "February - March",
        sowing_hi: "फरवरी - मार्च",
        harvest_en: "January - March",
        harvest_hi: "जनवरी - मार्च",
        active: true,
        risk_level: "Medium",
        images: [],
        about_en: "Sugarcane is a major commercial crop.",
        about_hi: "गन्ना एक प्रमुख व्यावसायिक फसल है।",
        diseases: [],
        tips_en: "Use trash mulching.",
        tips_hi: "ट्रैश मल्चिंग का उपयोग करें।"
    },
    {
        id: 9,
        name_en: "Potato",
        name_hi: "आलू",
        soil_en: "Sandy Loam",
        soil_hi: "रेतीली दोमट",
        season_en: "Rabi",
        season_hi: "रबी",
        duration: 90,
        sowing_en: "October - November",
        sowing_hi: "अक्टूबर - नवंबर",
        harvest_en: "January - February",
        harvest_hi: "जनवरी - फरवरी",
        active: true,
        risk_level: "Medium",
        images: [],
        about_en: "Potato is a major source of carbohydrates.",
        about_hi: "आलू कार्बोहाइड्रेट का एक प्रमुख स्रोत है।",
        diseases: [],
        tips_en: "Ensure proper earthing up.",
        tips_hi: "उचित मिट्टी चढ़ाना सुनिश्चित करें।"
    },
    {
        id: 10,
        name_en: "Tomato",
        name_hi: "टमाटर",
        soil_en: "Loamy, Sandy Loam",
        soil_hi: "दोमट, रेतीली दोमट",
        season_en: "Kharif / Rabi / Zaid",
        season_hi: "खरीफ / रबी / जायद",
        duration: 120,
        sowing_en: "June / October / February",
        sowing_hi: "जून / अक्टूबर / फरवरी",
        harvest_en: "September / February / May",
        harvest_hi: "सितंबर / फरवरी / मई",
        active: true,
        risk_level: "Medium",
        images: [],
        about_en: "Tomato is widely grown vegetable.",
        about_hi: "टमाटर व्यापक रूप से उगाई जाने वाली सब्जी है।",
        diseases: [],
        tips_en: "Use staking.",
        tips_hi: "स्टेकिंग का उपयोग करें।"
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { cropsData };
} else if (typeof window !== 'undefined') {
    window.cropsData = cropsData;
}
